version: "3.9"
services:
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/kc_clusters
      - REDIS_URL=redis://cache:6379
      - USE_SQLITE=false
      - ENFORCE_CSRF=true
    ports:
      - "5001:5001"
    depends_on:
      - db
      - cache
    command: ["python", "run_web.py"]
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kc_clusters
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  pgdata:

